name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch
  pull_request:
    branches:
      - main  # Set to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Add other dependencies here

      - name: Build the MkDocs site
        run: mkdocs build --verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Or your build directory
